### ISSUE TITLE
Request for complete raw 10X data

### ISSUE THREAD

**Issue by Sudolin** [chensujun/scRNA#3]
Dear Author,

Through analysis, we found taht the raw data of this article downloaed from GEO (GSE141445) is incomplete with loss of all mitochondrial genes expression. This would severely affect the clustering results and stop us from reproducing your findings. As such, we hope you could help us with uploading the original and unfiltered 10X data. Thanks.

Leo Lam
2021/10/10

**Comment by chensujun** [comment]
Hi Leo, 

All the analysis was based on the mitochondrial gene removed expression. The genes were used for QC only and the % mitochondrial gene expressed info can be find in the metadata file. 

Best,
Sujun

**Comment by Sudolin** [comment]
Thanks for your response.

Best,
Leo Lin

**Comment by erikagucciardo** [comment]
Sorry, does that mean that there is a Seurat Object(s) that can be used, since you mentioned the existence of a metadata file?
